#! /bin/bash

set -o errexit -o nounset -o pipefail

if (( ! "${#}" )) || [[ "${1}" = "-h" ]]
then
  echo "Usage: deja-dirs name [-c contains] [-b basedir] [-f filesource] [-d]" 1>&2
  exit 1
fi

CONTAINS=""
FILESRC=""
BASE="."
NAME="${1}"
shift

while getopts "c:b:f:d" OPT
do
  case "${OPT}" in
    c )
      CONTAINS="${OPTARG}"
      ;;
    b )
      OPTARG="$(realpath "${OPTARG/#\~/$HOME}")"

      if [[ -d "${OPTARG}" ]]
      then
        BASE="${OPTARG}"
      else
        echo "Base '${OPTARG}' is not a directory" 1>&2
        exit 1
      fi
      ;;
    d )
      set -o xtrace
      ;;
    f )
      OPTARG="$(realpath "${OPTARG/#\~/$HOME}")"

      if [[ ! -f "${OPTARG}" ]]
      then
        echo "'${OPTARG} is not a file" 1>&2
        exit 1
      elif [[ ! -r "${OPTARG}" ]]
      then
        echo "'${OPTARG} is not readable" 1>&2
        exit 1
      else
        FILESRC="${OPTARG}"
      fi
      ;;
    \? )
      # Just exit on error.
      exit 1
      ;;
    * )
      # Do nothing.
      ;;
  esac
done

shift $(( $OPTIND-1 ))

# A function to convert a relative path to a real, escaped Deja path.
# Since we're always passing this input from find, assume paths will
# always exist.
dejapath()
{
  # If we don't get exactly one argument, exit
  if [[ ! "${#}" -eq 1 ]]
  then
    return 0
  fi

  # Get the full path
  FULLPATH="$(realpath "${1}")"

  # To simplify the escaping logic, we always wrap in single quotes and
  # escape both double and single quotes in the file path. When using
  # gsettings set, the value is wrapped in double quotes. This could also
  # be achieved by wrapping single quotes in double quotes and doing extra
  # escaping, which is nearer to the way gsettings escapes the output, but
  # this ends up with more complex logic and a more complex output string.

  # Escape double and single quotes
  FULLPATH="${FULLPATH//\"/\\\"}"
  FULLPATH="${FULLPATH//\'/\\\'}"

  # Wrap in single quotes
  echo "'${FULLPATH}'"
}

# Get all occurrences of the directory that don't also have the directory
# in the path (e.g. nested node_modules directories).
if [[ -n "${FILESRC}" ]]
then
  mapfile -t < "${FILESRC}" FOUND
else
  mapfile -d "" -t FOUND < <(find "${BASE}" -name "${NAME}" -type d -print0 | grep -Fv "/${NAME}/" --null --null-data)
fi

FULLPATHS=()

for F in "${FOUND[@]}"
do
  if [[ -e "${F}" ]] && [[ -z "${CONTAINS}" || -e "${F}/${CONTAINS}" ]]
  then
      F="$(dejapath "${F}")"
      FULLPATHS+=( "${F}" )
  fi
done

# Write them out as a single comma-separated string.
DELIM=", "
printf -v OUTPUT "%s${DELIM}" "${FULLPATHS[@]}"
[[ ! "${OUTPUT}" = "${DELIM}" ]] && echo "${OUTPUT:0:-${#DELIM}}"
