version: 2
jobs:
  ubuntu-test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install git
          command: apt-get update && apt-get install git make -y
      - run:
          name: Install bats
          command: git clone https://github.com/sstephenson/bats.git ~/bats && ~/bats/install.sh /usr/local
      - run:
          name: Install deja-dirs
          command: make install
      - run:
          name: Run deja-dirs tests
          command: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - ubuntu-test
